# -*- coding: utf-8 -*-
"""News_Tiingo_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lotVFuaf04Quod9fmgGg2O0BprfflynB
"""

pip install tiingo

from tiingo import TiingoClient

config = {}

# To reuse the same HTTP Session across API calls (and have better performance), include a session key.
config['session'] = True

# If you don't have your API key as an environment variable,
# pass it in via a configuration dictionary.
config['api_key'] = "333019432fe95089c689230a0180e9d9b5efc0b8"

# Initialize
client = TiingoClient(config)

tickers = client.list_stock_tickers()

tickers

articles = client.get_news(tickers=['FB', 'AAPL'],
                            tags=['Laptops'],
                            sources=['washingtonpost.com'],
                            startDate='2017-01-01',
                            endDate='2021-01-01')

# After performing the above step, we have to first convert it into a dataframe and then get the csv file using inbuilt command.